### ISSUE TITLE
Switch from Gitlab's CI to GitHub actions

### ISSUE THREAD

**Issue by eponier** [jasmin-lang/jasmin#106]
One big advantage would be to have the CI results reported inside the PRs. A first try was attempted in https://github.com/jasmin-lang/jasmin/pull/96 but reverted in https://github.com/jasmin-lang/jasmin/pull/105 due to some limitations of the implementation.

Here is the list of points that were identified as blocking the replacement of GitLab's CI with GitHub's CI:

- [x] The OPAM cache gets corrupted regularly, so this should either be fixed or circumvented (e.g. by providing a nice way to clear the cache manually): done, see https://github.com/jasmin-lang/jasmin/pull/109
- [ ] The push-compiler-code job must not run on PRs (and other WIP branches), ideally only on some chosen branches, e.g. the protected branches
- [ ] GitLab's CI must be removed before merging if we are happy with GitHub actions

**Comment by maximedenes** [comment]
> * The OPAM cache gets corrupted regularly

Pointers to example failures welcome (maybe to Gitlab jobs, in fact, as it will be easier to verify that the fix is effective).

**Comment by eponier** [comment]
Here is a pointer to a failure of a GitHub job : https://github.com/jasmin-lang/jasmin/runs/6080469236?check_suite_focus=true.

**Comment by eponier** [comment]
The same failure on GitLab: https://gitlab.com/jasmin-lang/jasmin/-/jobs/2340273098.

**Comment by maximedenes** [comment]
@vbgl Is https://github.com/jasmin-lang/jasmin/commit/f5d67c23878204e4d60ccd7a604c9ccf83c938dd solving the cache issue mentioned above?

**Comment by maximedenes** [comment]
FTR, if you put a `#` before the issue number in the commit message, it will make a link appear here. We started looking at it before realizing it probably was already fixed (before spending a significant amount of time, fortunately).

**Comment by eponier** [comment]
What @maximedenes suggests for point 3 of the issue is to keep the two CI systems during a certain transition period, just to have the time to test it and make sure that the one based on Github Actions is working properly.

**Comment by eponier** [comment]
One way to have an automatic invalidation of the cache when changing the hash in `nixpkgs.nix` would be to include this hash in the key, either manually or automatically (probably some nix utility can print it?).

**Comment by eponier** [comment]
@maximedenes you may want to know that not only https://github.com/jasmin-lang/jasmin/pull/109 but also PR https://github.com/jasmin-lang/jasmin/pull/110 touched the GitLab CI. We certainly have to reflect these changes on GitHub's side. Would you mind doing that? I don't think that is a lot of work, but I can try to do it too if you want.

**Comment by eponier** [comment]
@vbgl found a way to report the CI status (run on Gitlab) to the corresponding PR (on GitHub). See for instance PR https://github.com/jasmin-lang/jasmin/pull/158. This is not as well integrated as using native GitHub CI, but should be enough to make it usable by anyone. Should we close this issue then? It seems that, at least in the near future, we are sticking to using GitLab for CI.

**Comment by maximedenes** [comment]
Sure, let's close this.
