### ISSUE TITLE
eclib is broken in latest version of EasyCrypt (2022.04)

### ISSUE THREAD

**Issue by vbgl** [jasmin-lang/jasmin#112]
Current version of `eclib/JModel.ec` is no longer accepted in latest versions of EasyCrypt:

The following proof line:
https://github.com/jasmin-lang/jasmin/blob/f5d67c23878204e4d60ccd7a604c9ccf83c938dd/eclib/JModel.ec#L38
fails with that error message:
> [by]: cannot close goals

git bisection leads to https://github.com/EasyCrypt/easycrypt/commit/a9748f75a4ec83fcbcd5b907e03996e6a2ada7e2

**Comment by fdupress** [comment]
Looks like a regression in the cost branch: `cbv` does not seem to reduce `edivn 3 `|16|` (the Euclidean division of 3 by |16|) to `(0, 3)`, which blocks further reduction.

I'll try to fix it here, but this should also be reported upstream, I think.

**Comment by strub** [comment]
No, the failure is genuine because when executing `cbv f`,  `cbv` tries to unfold `f` before trying to apply simplification rules. The proof ask for the unfolding of `edivz`, hence the operator is unfolded and no simplification can be done. The fix is easy: do not ask for the unfold of `edivz`.

**Comment by fdupress** [comment]
I literally just figured this out as well. Any thoughts about why this used to work?

**Comment by strub** [comment]
The breakage is new because we changed the ordering of the unfolding phase and the simplification phase. However, since the fix is easy, we are not going to revert this new behaviour.
