### ISSUE TITLE
Merging 'main' into 'glob_array3_slh'

### ISSUE THREAD

**Issue by tfaoliveira** [jasmin-lang/jasmin#144]
Given that `glob_array3_slh` branch contains the `get-random` features, which are needed in libjade, would it be possible to merge `main` into `glob_array3_slh`?

This would help to set up an environment where everything on libjade works. 

Thanks

**Comment by bgregoir** [comment]
yes for sur. I will do it tomorrow

**Comment by bgregoir** [comment]
It is done
