### ISSUE TITLE
More type checking

### ISSUE THREAD

**Issue by bgregoir** [jasmin-lang/jasmin#146]
VPMULL_16u8 is accepted by the typing and then compiled to an instruction that do not exists. 
The point is that the instruction exists but has no semantic. 
The type checking should be able to remove it. 
The semantic of the instruction generally check some condition on the size of the arguments. 
This should be done in a generic way using extra information provided in instr_desc.

**Comment by vbgl** [comment]
Using `VPMULL_16u8` now produces a type error:
> primitive “VPMULL” only accepts the following size annotations: _8u16, _16u16, _4u32, _8u32

Fixed by #490
