### ISSUE TITLE
Safety checker segfaults on Mac M1

### ISSUE THREAD

**Issue by mbbarbosa** [jasmin-lang/jasmin#168]
Not sure what this could be. It doesn't happen in my Mac x86.

$ lldb jasminc -- -I AES:src/aeslib -checksafety src/aeslib/aes.jazz
(lldb) target create "jasminc"
Current executable set to 'jasminc' (arm64).
(lldb) settings set -- target.run-args  "-I" "AES:src/aeslib" "-checksafety" "src/aeslib/aes.jazz"
(lldb) run
Process 96685 launched: '/usr/local/bin/jasminc' (arm64)
Default checker parameters.

Analyzing function aes_jazz
Process 96685 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=2, address=0x1011070a0)
    frame #0: 0x00000001011070a0
->  0x1011070a0: .long  0x011071b0                ; unknown opcode
    0x1011070a4: udf    #0x1
    0x1011070a8: udf    #0x6
    0x1011070ac: udf    #0x0

[Example.zip](https://github.com/jasmin-lang/jasmin/files/8878700/Example.zip)

**Comment by vbgl** [comment]
What version of OCaml are you using?

**Comment by vbgl** [comment]
Might be related: https://github.com/antoinemine/apron/pull/68

Let’s hope this issue gets resolved when the next version of `apron` is made available.
