### ISSUE TITLE
Unclear error when the result of a function does not match its type

### ISSUE THREAD

**Issue by eponier** [jasmin-lang/jasmin#17]
If the size of the return type of a function does not match the number of objects returned, such as in the following case
```
fn sum (reg u64[4] a) {
  reg u64 r; 
  
  r = a[0];
    
  return r;
}
```
the error mentions an `invalid number of arguments` (in the example `0 provided instead of 1`). It seems that arguments and results are treated in the same way. This is perhaps interesting from the developer point of view, but confusing from the user one.

**Comment by vbgl** [comment]
Fixed in `master` by e4f89e163dbee41816ff626fb85c2f30f49ba983 (also merged in `glob_array3`).
