### ISSUE TITLE
Pretyping rejects too many assignements to `const ptr`

### ISSUE THREAD

**Issue by vbgl** [jasmin-lang/jasmin#176]
The following program is rejected:

>  line 6 (2-3):
typing error: Cannot write to the constant pointer p

~~~
export
fn main() -> reg u64 {
  stack u64[1] s;
  s[0] = 0;
  reg const ptr u64[1] p;
  p = s;
  reg u64 r;
  r = p[0];
  return r;
}
~~~

I believe it should be accepted.

**Comment by eponier** [comment]
Hum, indeed there is a difference between a mutable pointer to const data and a const pointer to mutable data. If `reg const ptr` means the first, we must accept this example.

**Comment by vbgl** [comment]
Your help is welcome (I won’t work on a fix today)! I think you’ll have to look at line 1220 of `pretyping.ml`.

**Comment by vbgl** [comment]
See #178
