### ISSUE TITLE
Imprecise error in regalloc

### ISSUE THREAD

**Issue by eponier** [jasmin-lang/jasmin#24]
In the following code
```
fn f () -> reg u64 {
  reg u64 r;
  return r;
}

export fn main (reg u64 x) -> reg u64 {
  reg u64 r;
  r = f ();
  return r;
}
```
the regalloc pass fails with the message `Regalloc: unknown variable r.128`. If we initialize `r` in function `f`, the error disappears. Maybe the error should mention an uninitialized variable instead of an unknown one?

**Comment by eponier** [comment]
I slightly changed the error message to explain that the problem may come from an uninitialized variable.

@vbgl do you think there is a better fix?

**Comment by vbgl** [comment]
Here is a different fix that removes the error message altogether: 46754840033a61c9b3b4155a2d046e46afb4a0ac

**Comment by eponier** [comment]
Nice, I'll merge my PR and let you integrate your fix. Or do you want that I integrate it directly in my PR?

**Comment by vbgl** [comment]
AFAICT, your PR does not modifie `regalloc.ml`. I’ll thus merge this fix in `glob_array3` ASAP.
