### ISSUE TITLE
Problem running ec Prove

### ISSUE THREAD

**Issue by jonathan-dev** [jasmin-lang/jasmin#27]
Hi, I'm trying to run a simple example from [this](https://github.com/tfaoliveira/jasmin) repo but I keep getting the error below.
I think I had it running properly before but now I can't figure out what I have done differently before.

```
> /app/easycrypt/ec.native compile -I Jasmin:/app/jasmin/eclib/ addNv3_ct_proof.ec 
[critical] [: line 1 (0-24)] In external theory AddNv3_ct [./addNv3_ct.ec: line 2 (0-33)]:
In external theory JModel [: line 1 (0) to line 4 (58)]:
In external theory JWord [<unknown> location]:
unknown type `t'
[|] [0002] 4.6 % (-1.0B / [frag -1.0B])

```

Would be cool to get some hints on what I am possibly doing wrong.
Thanks

**Comment by strub** [comment]
Hi. In which branch of Jasmin are you?

**Comment by jonathan-dev** [comment]
I tried it on master and the constant-time
