### ISSUE TITLE
[x86] Add support for the vpmuldq instruction

### ISSUE THREAD

**Issue by dsprenkels** [jasmin-lang/jasmin#274]
Gregor Seiler's avx2 implementation for Dilithium makes extensive use of the [`vpmuldq`](https://www.felixcloutier.com/x86/pmuldq) instruction, see [`ntt.S`](https://github.com/pq-crystals/dilithium/blob/3e9b9f1412f6c7435dbeb4e10692ea58f181ee51/avx2/ntt.S). However, it does not seem to be supported (yet) in `jasminc`, see [`x86_instr_decl.v`](https://github.com/jasmin-lang/jasmin/blob/716cf442660831af9726c6f69a746c08f4363b85/proofs/compiler/x86_instr_decl.v). Could support for this instruction be added to the compiler?

**Comment by vbgl** [comment]
Yes, this instruction can be supported.

Do you want to give it a try? There are some instructions there: https://github.com/jasmin-lang/jasmin/wiki/Howto-Add-Instructions

**Comment by dsprenkels** [comment]
@vbgl Yes I'd like to take a shot at it :)

**Comment by dsprenkels** [comment]
@vbgl I opened a pull request :tada:
