### ISSUE TITLE
eclib: no matching operator, named `VMOVSHDUP_4u64'

### ISSUE THREAD

**Issue by tfaoliveira** [jasmin-lang/jasmin#301]
I'm integrating this [implementation](https://github.com/dsprenkels/libjade/blob/7f9addcea5ba940cd543eff2e62eeb95244653d4/src/crypto_sign/dilithium/common/amd64/avx2/ntt.jinc#L185) in [libjade](https://github.com/tfaoliveira/libjade/tree/dilithium-avx2-integration). 

When checking the extracted file with `easycrypt` I get the following error:
```
[critical] [sign_s.ec: line 2564 (14-28)] no matching operator, named `VMOVSHDUP_4u64', for the following parameters' type:
  [1]: W256.t
[-] [5972] 100.0 % (-1.0B / [frag -1.0B])
```

It seems that a def. for `VMOVSHDUP_4u64` is missing in [JModel.ec around line 673](https://github.com/jasmin-lang/jasmin/blob/de18c89863501eab67cf8558cfc230fcf12b6873/eclib/JModel.ec#L673).

**Comment by vbgl** [comment]
That’s unfortunate, but the `VMOVSHDUP_4u64` has no semantics in Jasmin. For the time being, you can rename it into `…_8u32`.
IMHO, this syntactic flexibility (many variants are accepted by the parser, but only a few make sense) is misleading, hence the related PR. What do you think?

**Comment by tfaoliveira** [comment]
I think it's OK. Once PR is merged, I can update the libajde code. Thanks.
