### ISSUE TITLE
Progress on clear stack

### ISSUE THREAD

**Issue by eponier** [jasmin-lang/jasmin#330]
Tasks:
- finalize the feature
  - [ ] define the proof scheme (with @bgregoir) (1.5/3)
  - [ ] show semantic preservation (0/3)
  - [ ] show that the code correctly writes 0s (0/1)
  - [ ] show that there are no write outside the cleared zone (10.5/10)
- [ ] Tests: 4-5 programs which use the feature (big alloc size, big call depth, different clear step sizes) (0/2)
- [ ] Documentation: in the wiki (0/3, if enough time)
- [ ] Demo (0/2):
  - code compiled with or without clearstack
  - show the generated code in both cases
  - read in the memory to retrieve (or not) some secret data (with gdb?) with @maximedenes and @bgregoir

**Comment by eponier** [comment]
With @bgregoir, we identified a few invariants to establish in the proof of linearization.

**Comment by eponier** [comment]
The invariants seem to work. I have to check that the proof of the call works, and then I'll admit some parts to check whether we can prove the final theorem for the whole compiler.

**Comment by jedisct1** [comment]
Maybe that one can now be closed :)
