### ISSUE TITLE
WARNING: CAN NOT FIND IINFO

### ISSUE THREAD

**Issue by eponier** [jasmin-lang/jasmin#37]
When trying to print some `iinfo`, I get this warning. Maybe a variable introduced by the compiler not the right way. I will try to give a minimal example later.

**Comment by vbgl** [comment]
This warning has been removed: https://github.com/jasmin-lang/jasmin/commit/512b86cb6120a67f6b76e27663715342cc14e7f8#diff-3366da86ae1369ef11d4015b6861bbd3218b4eede94dc73739bd7a514d5602f5L224
