### ISSUE TITLE
Fix SETcc instruction handling

### ISSUE THREAD

**Issue by MQuaresma** [jasmin-lang/jasmin#39]
After discussing with Benjamin, it seems the behaviour of the Jasmin compiler regarding the `#SETcc` instruction/intrinsic is not intuitive at times.
Consider the following block of code:

```
export fn test(reg u64 p p1 p2) -> reg u8
{
  reg u8 s t8;
  reg bool cf sf of zf pf;

  of, cf, sf, pf, zf = #CMP(p, p);
  s = #SETcc(cf || zf);

  return s;
}
```
which compiles correctly and checks if `p <= p` using the `SETBE` instruction.

If the `SETcc` instruction is called as follows (swapping the `cf` and `zf` flags):
```
s = #SETcc(zf || cf);
```

the compiler returns the following error:

```
compilation error in functions test and test at position line 7: assembler error Invalid condition (BE)
```

although `cf || zf` and `zf || cf` are logically equivalent.

**Comment by vbgl** [comment]
Fixed in 2022.04.0.

Note that in current `main` branch (not released yet), the same program can be more conveniently written as follows:

~~~
  reg bool le;

  ?{ "<=u" = le }= #CMP(p, p);
  s = #SETcc(le);
~~~
