### ISSUE TITLE
Register allocation bug with instrinsics

### ISSUE THREAD

**Issue by sarranz** [jasmin-lang/jasmin#455]
The following fails
```
export
fn main(reg u64 y) {
    reg u64 x;

    // Commenting either of the following two lines makes compilation succeed.
    x = #MOV(y);  // Using x = y; makes compilation succeed.
    x = 1;

    x = y if x == 0;
    [x] = x;
}
```
with `internal compilation error in function main: Variable allocation: y (defined at "../bug.jazz", line 2 (16-17)) and RDI (defined at "", line -1 (-1)) : variable already set`. Removing any of the four instructions makes compilation go through, as well as using an assignment instead of `MOV`.

**Comment by vbgl** [comment]
Well spotted. Register allocation does indeed something wrong.

Confirmed in 2022.09, but not in 2022.04.
