### ISSUE TITLE
Unclear register allocation error about "conflicting register"

### ISSUE THREAD

**Issue by eponier** [jasmin-lang/jasmin#523]
The code

```
export fn main () -> reg u64 {
  reg u64 res;
  reg u64 rot1 rot2;

  res = 0;
  rot1 = 0;
  rot2 = 0;
  res <<r= rot1 & 63;
  res <<r= rot2 & 63;

  res += rot1;
  res += rot2;

  return res;
}
```

produces the error

```
"reg_conflict.jazz", line 9 (2-21):
compilation error:
register allocation: variable rot2.210 must be allocated to conflicting register RCX { rot1.209 }
```

The message is a bit hard to understand (but I did not notice at first that the problematic line was given).

But the set `{ rot1.209 }` is not explained. Maybe something like variable `rot2.210 must be allocated to register RCX, but conflicts with variable rot1.209 that is already assigned to it` would already be clearer?

I think a better message would mention that `ROL` needs its second argument to be in `RCX`, giving a better insight of where the error comes from.

Reported by @sabrinamanickam.

**Comment by vbgl** [comment]
PR #527 proposes a rewording of this message into:

> "compiler/tests/fail/register_allocation/x86-64/bug_523.jazz", line 9 (2-21):
compilation error:
register allocation: variable rot2.212 must be allocated to register RCX due to architectural constaints; this register already holds conflicting variable: rot1.211

Is it better?

**Comment by sabrinamanickam** [comment]
Yes, I think this message is much better. Thank you.
