### ISSUE TITLE
error in “one-varmap” checker: modified expression

### ISSUE THREAD

**Issue by eponier** [jasmin-lang/jasmin#56]
The file `tests/fails/spill.jazz` reveals a bug in the register allocation. The allocator tries to use `RAX` for the return address of the called function `gosub` while it is already used in the callee `main`. Apparently it does not take into account all the registers that are live in the callee.

**Comment by eponier** [comment]
Benjamin also finds surprising that the allocator does not decide on its own to put the return address on the stack when it detects that it does not have enough registers at hand. But maybe the allocator only tries that option when the option has been manually given?

**Comment by vbgl** [comment]
At commit 4739cb65, the error message used to be:

> compilation error in functions main and main at position line 19: Need to spill 
RAX { r.381 }

**Comment by eponier** [comment]
Hum, so there is something fishy about the removal of the error `Cerr_need_spill`.

**Comment by eponier** [comment]
Ok, I discussed with Benjamin. Before, the checker was backward, so we failed at the call sites when seeing a live register modified by the call. Now the checker is forward, we maintain a set of registers not to be used, and we fail at the first instruction after the problematic call site that assigns a register in that set. We think that it is enough to attach to each variable in that set one or several locations explaining why they are in that set. These locations will allow to give sufficiently nice error messages.

**Comment by eponier** [comment]
Summary of a discussion: something specific (and maybe a bit fishy) was done for registers holding the return address. But the bug is also present even when using `#[returnaddress="stack]`, so an investigation is needed. It has not been decided yet whether the Coq checker is expected to never fail (which means that the error is always caught early by the OCaml code).

**Comment by vbgl** [comment]
The register allocation treats differently conflicts within a single function and conflicts with the callers: https://github.com/jasmin-lang/jasmin/blob/5231b52c77290d26e78d0a14706d1ae90e5a8ccd/compiler/src/regalloc.ml#L314-L315

The current implementation continues (picks a register that will be in conflict somewhere) but could stop or at least emit a proper error message.

**Comment by eponier** [comment]
So it does the same as for the return address? It knows something is wrong but continues nonetheless?

**Comment by vbgl** [comment]
Yes, so that you get a neat “need-to-spill” error message on the call-site (irony).

**Comment by eponier** [comment]
So it really remains to be decided whether we want to fail early in OCaml or later in Coq.

**Comment by eponier** [comment]
And to be complete, there are other errors that are caught by Coq (and that are different from what they were before). Note that all the examples have uninitialized variables.

With
```
export fn main (reg u64 x) -> reg u64 {
  reg u64 res;
  return res;
}
```
before: `error in “one-varmap” checker: function main has free variables among res`
now: compiles (??)

With
```
export fn main (reg u64 x) -> reg u64 {
  reg u64 res;
  reg u64 z;
  res = z;
  return res;
}
```
before: `error in “one-varmap” checker: function main has free variables among RAX`
now: `one-varmap checker: not able to ensure equality of the result`

With
```
export fn main (reg u64 x) -> reg u64 {
  reg u64 res;
  reg u64 z;
  z += res;
  res = z;
  return res;
}
```
before: `error in “one-varmap” checker: function main has free variables among RAX; RCX`
now: `one-varmap checker: modified expression`

**Comment by eponier** [comment]
There again, errors were rather clearer before.

**Comment by vbgl** [comment]
Jasmin 2022.04.0 no longer fails on these examples.
