### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by samyuktha123sets** [jasmin-lang/jasmin#598]
Dear Team,

I am carrying out the installation of Jasmin and faced with this error when I executed nix-shell default.nix.
kindly help in resolving the issue
![image](https://github.com/jasmin-lang/jasmin/assets/99633453/eaf4a1a8-d93c-43ec-861b-a6fe343ef633)

Regards
Samyuktha

**Comment by vbgl** [comment]
There is an extra `sudo` at the beginning of your command…

**Comment by eponier** [comment]
I'm closing, I hope you problem is solved. For this kind of problem, please prefer contacting us on [Zulip](https://formosa-crypto.zulipchat.com/).
