### ISSUE TITLE
VAES support

### ISSUE THREAD

**Issue by jedisct1** [jasmin-lang/jasmin#630]
On x86_64, the `[V]AES{DEC,DECLAST,ENC,ENCLAST}` intrinsics only support `u128`operands. Same for `PVCLMULQDQ`.

This is sad, because many Intel and Intel-compatible CPUs support `2u128` operands with the same throughput/latency.

Would it be possible to add support for VAES in a future release?

Thank you!

**Comment by bgregoir** [comment]
Yes, this is a trivial patch.
