### ISSUE TITLE
Compiler pass "add array init" creates a lval with a dummy location

### ISSUE THREAD

**Issue by eponier** [jasmin-lang/jasmin#718]
The instruction itself has a location, but not the lval. I do not know what to do here, maybe there is no good solution.

**Comment by eponier** [comment]
(The corresponding line is https://github.com/jasmin-lang/jasmin/blob/3f92895d90a6e13572881405146de3dce77ef9a9/proofs/compiler/array_init.v#L94)

**Comment by J08nY** [comment]
This may be possible to solve the same way as in: https://github.com/jasmin-lang/jasmin/pull/736/commits/c727337ae604edf5277e5903d5680752eb54bb59. There the dummy flag variables __of__, __zf__, ... did not have any variable info.
