### ISSUE TITLE
Unexpected operator unspill

### ISSUE THREAD

**Issue by eponier** [jasmin-lang/jasmin#719]
Compiling
```
export fn main () -> reg u64 {
  reg u64 res;

  res = 0;
  () = #unspill(res);

  res = 1;
  return res;
}
```
gives
```
"file.jazz", line 5 (2-21):
internal compilation error in function main:
  asmgen: assemble_sopn: unexpected operator unspill
Please report at https://github.com/jasmin-lang/jasmin/issues
```

**Comment by vbgl** [comment]
I think this is a bug of the `lower_spill` phase that has the following optimization: it does nothing when there are no spilled variable (although it should assert that there are no spill/unspill operators in the function body).

A similar crash occurs when there is a single `() = #spill();` (no arguments) in a function.
