### ISSUE TITLE
Fatal OCaml error when using an inline bool as a flag

### ISSUE THREAD

**Issue by sarranz** [jasmin-lang/jasmin#87]
This (incorrect) Jasmin program
```
export fn bad () -> reg u64
{
  reg u64 r;
  inline bool zf;

  r = 0;
  ?{zf}, r = #ADD(r, 1);

  return r;
}

```
fails with
```
Fatal error: exception Not_found
Raised at Stdlib__hashtbl.MakeSeeded.find in file "hashtbl.ml", line 389, characters 17-32
Called from Regalloc.X64.forced_registers.f in file "src/regalloc.ml", line 536, characters 14-38
```

**Comment by vbgl** [comment]
Thanks for the report. I propose a fix there: https://github.com/jasmin-lang/jasmin/pull/88 Your feedback is appreciated.

**Comment by sarranz** [comment]
Looks good. Can this error happen for some other reason than mixing up inline and reg/stack? If not, perhaps it would be worth mentioning that in the error?

**Comment by vbgl** [comment]
I don’t know. When I first wrote this code, I thought that the error could never happen…

**Comment by sarranz** [comment]
Then perhaps we could have this message. But with these changes it's already good.

**Comment by vbgl** [comment]
I’ve just made the message a bit more verbose.
