### ISSUE TITLE
Feature Request BTR/BTS

### ISSUE THREAD

**Issue by kraemv** [jasmin-lang/jasmin#928]
Hello everyone,

could we add the BTR and BTS instruction to the x86 intrinsics? These instructions perform a BIT test and reset/set.
https://www.felixcloutier.com/x86/btr
https://www.felixcloutier.com/x86/bts
These instructions are useful for clearing/setting specific bits without using AND/OR masks.

Cheers,
Vincent

**Comment by vbgl** [comment]
Welcome. Thanks for your interest in Jasmin.

The documentation for these instructions imply that their behavior is not the same when they target a memory location or a register. I guess that the memory case would be hard to add to jasmin. Would you be satisfied if these instructions were only allowed on registers in jasmin programs?

**Comment by kraemv** [comment]
Yes, registers are fully sufficient for me! Thank you, for the quick response.

**Comment by vbgl** [comment]
Fixed in #932.
