### ISSUE TITLE
Missing error for invalid vector right shift

### ISSUE THREAD

**Issue by kraemv** [jasmin-lang/jasmin#950]
Hello everyone,

I am using Jasmin Compiler 2023.06.1. My compiler compiled the following instruction:
a = #VPSRA_4u64(a, 63);
AVX2 extensions do not allow Quadword shifts, so this should throw an error.

Thanks,
Vincent

**Comment by vbgl** [comment]
Thanks for the report. This sounds easy to fix.

**Comment by vbgl** [comment]
Fixed in #955.
